### ISSUE TITLE
PHP8  Serialization error

### ISSUE THREAD

**Issue by semanticfire** [theseer/fDOMDocument#40] opened 2021-11-29 10:35 UTC
On PHP 7.4 Serialization work with serialize($fdominstance) on PHP 8.1 I get: Serialization not allowed

**Comment by theseer** [comment] 2021-11-29 11:47
This error is new in PHP 8.1 - which doesn't allow serialization for "unserialisable" things. That also applies for the underlying `DOMDocument`:

```php

 $d = new DOMDocument();
 $d->loadXML('<?xml version="1.0"?><root/>');

 var_dump(serialize($d));
```

```
PHP Fatal error:  Uncaught Exception: Serialization of 'DOMDocument' is not allowed in test.php:6
Stack trace:
#0 test.php(6): serialize()
#1 {main}
  thrown in test.php on line 6
```

I don't think that is actually a problem as  even in PHP < 8.1, this doesn't really work as you cannot properly unserialize it:

```php
 $d = new DOMDocument();
 $d->loadXML('<?xml version="1.0"?><root/>');

 $s = serialize($d);

 $n = unserialize($s);

 var_dump($n->saveXML());
```

```
PHP Warning:  DOMDocument::saveXML(): Couldn't fetch DOMDocument in test.php on line 11
PHP Stack trace:
PHP   1. {main}() test.php:0
PHP   2. DOMDocument->saveXML() test.php:11
```

So, long story short: There is nothing I can do here unless I actually implement Serializable?

**Comment by semanticfire** [comment] 2021-11-29 12:01
Okay, that is interesting, let me check how it is actually used in my application, and how the unserialize does generate useful output.

**Comment by theseer** [comment] 2021-11-29 19:12
I'll close this, as this is not a problem caused by fDOMDocument and there is nothing we can do here to avoid the situation.

**Closed by theseer** 2021-11-29 19:12 UTC
Labels: Under Investigation

**Comment by semanticfire** [comment] 2021-11-29 19:20
So the 'issue' was in my code

in 7.4
`$x = $y` ( where $y is a stdclass object ) creates a new copy, I serialize $x for caching and add a fDomDocument instance to $y for further processing.
in 8.1 this created a reference, resulting in that $y also has the fDomDocument instance and chocking on the serialize
`$x= clone $y` solved my problem

My only issue is that I can't find the docs to explain this.

**Comment by theseer** [comment] 2021-11-29 19:28
I'm not sure I understand that solution nor believe your explanation:

```
$y = new StdClass;
$y->d = new DOMDocument();

$x = $y;

var_dump(spl_object_id($y->d));
var_dump(spl_object_id($x->d));

var_dump(spl_object_id($x));
var_dump(spl_object_id($y));
```

PHP 8.1:
```
theseer@nyda ~ $ php81 test.php
int(2)
int(2)
int(1)
int(1)
```


PHP 8.0:
```
theseer@nyda ~ $ php test.php
int(2)
int(2)
int(1)
int(1)
```


PHP 7.4:
``theseer@nyda ~ $ php74 test.php
/home/theseer/test.php:8:
int(2)
/home/theseer/test.php:9:
int(2)
/home/theseer/test.php:11:
int(1)
/home/theseer/test.php:12:
int(1)
```

There's no copy created, it's always the very same identical object.
`

**Comment by theseer** [comment] 2021-11-29 19:32
Even when adding `serialize` and `unserialize` to the mix, it doesn't work:

```php

$y = new StdClass;
$y->d = new DOMDocument();
$y->d->loadXML('<?xml version="1.0"?><root/>');

$x = $y;

$s1 = serialize($y);
$s2 = serialize(clone $y);

$x1 = unserialize($s1);
$x2 = unserialize($s2);

var_dump($x1->d->saveXML());
var_dump($x2->d->saveXML());
```

PHP 7.4:
```
PHP Warning:  DOMDocument::saveXML(): Couldn't fetch DOMDocument in /home/theseer/test.php on line 15
PHP Stack trace:
PHP   1. {main}() /home/theseer/test.php:0
PHP   2. DOMDocument->saveXML() /home/theseer/test.php:15
/home/theseer/test.php:15:
NULL
PHP Warning:  DOMDocument::saveXML(): Couldn't fetch DOMDocument in /home/theseer/test.php on line 16
PHP Stack trace:
PHP   1. {main}() /home/theseer/test.php:0
PHP   2. DOMDocument->saveXML() /home/theseer/test.php:16
/home/theseer/test.php:16:
NULL
```

**Comment by semanticfire** [comment] 2021-11-29 19:34
Is this the right medium to discuss?

**Comment by theseer** [comment] 2021-11-29 20:20
Probably not. I'm just curious to understand what is happening and why your code might have worked before as I cannot see how that would have been possible ;)

If you're interested, we could do a video session on that tomorrow some time?
